language: go
go:
- 1.3.1
env:
  global:
  - secure: oVqYvrmz08cbe2BmC9RNn42pGTIMVyI/s3rF0x/aNXGdHlLJRQbwHn2+cMJ9tQGIbtnt+Cl6LMcQYQlFnwz6ZCA4DqEDm6Aa9eZWAtzYoNSyfsKSdAGrVr8qx42csP/1angmO9+4b/x2onczuT6F1eLiEfcmDsnVot/rIKL5aHY=
  - secure: V6LAJznLGKUCXtXRE8ezT41CVZ6W1GHabRC7ewPJufK51qtx02QBcNzW6nXtWXROK/Yw8xu+RPfSA9i0M33tD+rt/TNZWb/THaW5gT/gGg6ZNo0liVyG7y2OvRbj5FhYH1NqKvoKUMQHJOCrGaFusVnm/ZrF9ePUlndlfsNfrK0=
before_script:
- go get gopkg.in/check.v1
- go get code.google.com/p/go.tools/cmd/cover
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- export PATH=$PATH:$HOME/gopath/bin/
after_success:
- goveralls -coverprofile=cov.out
script:
- go test -covermode=count -coverprofile=cov.out
